version: '3'
services:
  pylanthia:
    build: .
    ports:
      - "4901:4901"
    volumes:
      - ./vendor/lich:/lich:consistent
      - .:/pylanthia:consistent
    entrypoint: "/bin/bash -c"
    command: "/pylanthia/start.sh"
